### ISSUE TITLE
Update Net Zero scenario to fix Kigali Amendment policy setting

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#101]
We noted the policy schedule for f-gas substitution was off in the FoPITY file for the Net Zero scenario. Let's update this ASAP and push.

**Comment by jrissman** [comment]
If you want this change public, this will require a 3.0.0.1 (e.g. data-only revision) model release.  Please try to make sure you have no other data updates to make before we push this, so we can roll any necessary data updates into the same release (for instance, if you plan to tweak Net Zero in other ways).  When you are satisfied that the reference scenarios and other input data are final, let me know what Git branch it's in, and Todd and I can process it as a model release.  (I'll roll some doc updates into that release as well.)

**Comment by jrissman** [comment]
Since there has now been a structural change (#102), the next release will be 3.0.1, not 3.0.0.1.

**Comment by mkmahajan** [comment]
Completed in commit 3210cdf
