### ISSUE TITLE
Fix #REF errors and graphs in elec/FPC

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#104]
There are many "REF" errors and the graphs are messed up on the "Curtailment Calcs" tab of the variable `elec/FPC` (in the Excel file).  This should be fixed as part of the next EPS input data update.

**Comment by robbieorvis** [comment]
I think this may have been introduced while @mkmahajan was making some calibration adjustments, so reassigning.

**Comment by mkmahajan** [comment]
Resolved in commit d902d7c.
