### ISSUE TITLE
Modify changes in electricity costs to correctly capture recovery of costs over asset/financing lifetime instead of having one year cost changes

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#109]
Currently in the EPS changes in power sector costs incurred as a result of policy are incurred in the same year they occur, with all costs passed through in a single year. In practice, utility bills are used to recoup these costs over the lifetime (more or less of an asset). So a power plants costs would be passed onto customers over ~30 years instead of all in a single year.

We should try to reflect this when modifying changes in electricity prices in combination with adding in financing policies in a subsequent EPS update. This would help smooth induced jobs effects and better reflect how rates/bills change in response to policy.

**Comment by jrissman** [comment]
Merged into issue #72
