### ISSUE TITLE
Move to NYMEX gas futures prices for natural gas price projections

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#112]
After discussions with other modelers today it seems as if the gas prices in AEO are too high relative to most other forecasts. Other models sometimes use the NYMEX gas futures prices (https://www.cmegroup.com/trading/energy/natural-gas/natural-gas.html). We should move to using this for model, and scale sector prices based on the sector prices in AEO relative to the Henry Hub price in AEO.

**Comment by mkmahajan** [comment]
Noting that we have decided to leave our current AEO prices in for now.

**Comment by robbieorvis** [comment]
We recently updated with with the AEO 2021 update.

**Comment by robbieorvis** [comment]
Done in commits 05d8535dcbac79e7221d213873ef673c8f0534a1 and 32472cce68208357d4c831ef02969c59e5badd15
