### ISSUE TITLE
Bug in policy schedule implementation for TDM policies

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#114]
We discovered today that setting TDM policies was causing the model to crash, which flagged a bug in Vensim. In the new policy schedule implementation methodology for the revised TDM levers, the schedule calculation is not correctly subscripted by policy element, and so all elements relate back to the LDV passenger policy schedule setting.

**Comment by jrissman** [comment]
I think you might be misinterpreting the syntax of the GET ELM MAP() function.  It's supposed to contain a reference to the first element of the subscript from which you want to start mapping.  Look at the equation inside another subscripted policy lever's "This Year" version to see other examples, like "Boolean Rebate Program for Efficient Components This Year."

I'll run some tests to see if it's working or not.

**Comment by robbieorvis** [comment]
Ah okay – yes in that case I was misinterpreting. However, there is still a crash (we are using the eps-nevada model on the develop branch; you can replicate the issue by just turning on a freight HDV TDM policy (I used a value of 0.22).

-R

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
In my testing of the U.S. EPS, this policy obeys the schedules for each subscript element normally.  I don't encounter an issue where it is using the first element's schedule for all elements.  (The easiest way that can happen if you forget to set the Policy Implementation Schedule selector to the custom schedule you made, because the default schedule contains the same setting for every element of every policy.)

I'll look into the crash using EPS Nevada because I can't recreate any problematic behavior in the U.S. EPS.

**Comment by jrissman** [comment]
Does eps-nevada have a repo?  If so, maybe I was never invited as a collaborator.  I don't see it in the EI account's repo list.

**Comment by robbieorvis** [comment]
It’s a private repo on the EI GitHub account – you should see it there

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
I do not see it there.  I can log in as EI GitHub admin and make sure I was added as a collaborator, which is necessary to see private repos when logged in as myself.

**Comment by robbieorvis** [comment]
Oh yes, I thought that’s what you were planning to do.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
It looks like EPS Nevada is running on an outdated model version.  The updated policy schedules don't work without the updated EPS.mdl and EPS.vpmx files that are intended to use those schedules.

InputData/version.txt is also not up-to-date.

Whenever updating a regional model to the latest platform, it may be good to double-check that all changed files have been copied in from the U.S. EPS.

**Comment by jrissman** [comment]
Wait, I may have been looking at the wrong branch.  Hold on.

**Comment by robbieorvis** [comment]
I think I see what may be the source of the problem, though not the cause. Freight aircraft have 0 cargo distance transported demand in BAU and zero vehicles, which I think is why we are seeing an error. But I’m not quite sure how this plays out with the new structure.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Those freight figures shouldn't be a problem, if they are accurate for Nevada.

Right now, I'm investigating whether the Nevada multipliers in the I/O model are too high for non-road vehicle manufacturers.  When you shift from freight HDVs, it goes to freight rail.  That boosts the non-road vehicle manufacturers' ISIC code.  If that ISIC code has unreasonable multipliers, any but the smallest boost to that ISIC code can cause a crash.

**Comment by robbieorvis** [comment]
One extremely odd thing is that when I toggle on the freight HDVs lever to any policy setting, and I click on Table, it shows zeroes. I have no idea what that’s about – never seen it before, unless it’s doing that because of the calculation error.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Incidentally, you have `trans/RTMF` set up to send 10% of cargo from freight HDVs freight ships, and that would be quite a feat in Nevada!

**Comment by robbieorvis** [comment]
Well – it’s seeming to work with smaller policy values than 0.2 (I tried 0.01 and no error)

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
> One extremely odd thing is that when I toggle on the freight HDVs lever to any policy setting, and I click on Table, it shows zeroes. I have no idea what that’s about – never seen it before, unless it’s doing that because of the calculation error.

If Vensim crashes, it doesn't necessarily report correct values for any variable, even in timesteps prior to the crash.  This is one way Vensim makes it hard to debug crash issues.

**Comment by robbieorvis** [comment]
Okay, I think this may eventually come down to a data issue. When I turn on the policy setting for HDV freight to 0.05, I can see a huge drop in cargo distance transported in later years as a product of some feedback effect. I’m trying to trace where this is stemming from, but my guess is it’s an input data issue.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
It looks like `io-model/DCSoCbIC Domestic Content Share of Consumption by ISIC Code` is probably far too high.  I cannot believe that such overwhelming percentages of things purchased in Nevada were made by Nevada businesses.  I thought RMI had a script-based methodology or data source to downscale `DCSoCbIC` to the state level.  (A procedure I once suggested to Jun to produce `DLIM` for state-level models relies on having `DCSoCbIC` data, so if you don't have reasonable `DCSoCbIC` data, maybe `DLIM` isn't reasonable either, though I haven't checked `DLIM` directly yet.

**Comment by robbieorvis** [comment]
Turning off the macroeconomic effects eliminated the problem, and I’m noticing massive job and GDP impacts, far too big to be from this little policy. We need to double check the input data.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by robbieorvis** [comment]
They do, and we have flagged this multiple times for them. Let us circle back to them on this.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by robbieorvis** [comment]
I see – the .xlsx file is correct but it didn’t get exported to .csv. You can close this issue.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
As a good starting point, why don't you try using the "Input Data Debugging Helper" I made for EPS Virginia.  Using that tool should probably be a standard part of calibration now that we have an IO model.  That will check the reasonableness of DLIM and the three within-industry intensity multipliers.  (It does not check `DCSoCbIC`, but maybe it should.)

**Comment by jrissman** [comment]
Okay, I'll close it.
