### ISSUE TITLE
Create new control lever to remove exported electricity emissions from totals

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#118]
In China, provincial emissions accounting includes imported electricity emissions and excludes exported electricity emissions. The EPS already has a way to handle imported electricity emissions being added to totals. 

We should add a control lever that would allow for removal of exported electricity emissions from totals.

The lever could simply reduce total electricity sector emissions by the share of electricity generation that is exported; nothing fancy needed. 

This will be important for building out the provincial models in China.

**Comment by jrissman** [comment]
Completed in be3ae3d.
