### ISSUE TITLE
Break down transmission costs by ISIC code

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#120]
Suggested by Robbie. Currently, all costs are assigned to the construction ISIC code in the variable 'Electricity Sector Change in Amount Spent on Capital Equipment and OM by ISIC Code.'

**Comment by jrissman** [comment]
For other things like this, Robbie or you provided me with a spreadsheet with fractional cost breakdowns by recipient ISIC code.  Do you want to create one for transmission construction costs?  Implementing it in Vensim is pretty quick.

**Comment by mkmahajan** [comment]
Yes, I am assigning myself to this issue as well and will search for some data. I likely won't get to this immediately, but will be sure to set up a file before this would be incorporated in the next update (after 3.1).

**Comment by jrissman** [comment]
Sounds great!  No hurry on my end :-)

**Comment by robbieorvis** [comment]
FYI @mkmahajan there is an NREL JEDI model for transmission, which would be a perfect place to get this. It's where I got the other data for the power sector. You can find it here: https://www.nrel.gov/analysis/jedi/models.html

**Comment by jrissman** [comment]
It strikes me that we could implement this without altering the Texas EPS results by assigning a 100% share to the "construction" ISIC code in the Texas EPS dataset.  So if you'd like me to include this feature for 3.1, just send along the file that divides up the costs of building transmission lines by recipient ISIC code for the U.S. nationally, and I should be able to do it promptly.

**Comment by mkmahajan** [comment]
I'll try to get this file set up tomorrow so we can sneak it into 3.1 - thanks!

**Comment by mkmahajan** [comment]
Hi @jrissman - I put together a new file that breaks down transmission costs by ISIC code, attached here
[Share of Transmission Capital Costs by ISIC Code.xlsx](https://github.com/Energy-Innovation/eps-us/files/5631507/Share.of.Transmission.Capital.Costs.by.ISIC.Code.xlsx)

**Comment by jrissman** [comment]
Thank you for that file, Megan!

This is completed in 76f296e.
