### ISSUE TITLE
ELF for hydrogen should use the district heat and hydrogen sector subscript, not industry

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#128]
Hydrogen supply is likely to be very flexible. To be able to model this correctly without updates to our demand response methodology (mentioned in the previous issue), we should use the district heat and hydrogen subscript, not the industry subscript to which it is currently mapped (we should map it this way anyway, even without the DR update). ELF has been updated to account for this but the structure needs a slight fix.

This is needed for the US 3.1 model to work correctly. For TX, we can use the industrial values for district heat and hydrogen to avoid changing their data.

**Comment by jrissman** [comment]
Completed in 3833139
