### ISSUE TITLE
Update to an IO data source with full global coverage and much improved sectoral breakdowns

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#133]
I found a published, international (covering 277 regions) dataset, with very detailed sectoral coverage, called EXIO Database. I was finally able to access the data. You can find it here: https://zenodo.org/record/3583071#.X_TYsNhKhaQ

This dataset contains extremely detailed data for nearly every country on supply, use, value added (and subcomponents), and IO tables, both domestic and foreign. It contains very detailed energy supply and consumption data as well as detailed data on different electricity sources. It is also regularly updated, incorporating new data as published.

Down the road, it would be a significant improvement to update to this datasource, replacing the OECD data, for the IO data, since it has significantly more sectoral detail and full international coverage. It would be a much undertaking however.

I am marking in low priority since it would represent a major undertaking and is probably out of scope from 2021, but would love to revisit in the future.

**Comment by jrissman** [comment]
The link above is to EXIOBASE version 3.7.  However, in Nov 2020, version 3.8 of EXIOBASE was relased, which appears to include coverage of more recent years than version 3.7.  The link to version 3.8 is https://zenodo.org/record/4277368

Whenever we get around to looking at EXIOBASE more closely, we should first check the "Versions" box in the right-hand column of that page and make sure we're using whatever the latest version is at the time.

Also, I tried to view the downloaded database files, but despite having a ".csv" extension, they are not comma-delimited.  They seem to be delimited by the pipe character (i.e. "|"), but even after converting the pipe characters to commas and opening it as a .csv in Excel, the data aren't really readable.  The README file suggests using the viewer program Pymrio available at: https://github.com/konstantinstadler/pymrio

The site for Pymrio says:

> Pymrio is an open source tool for analysing global environmentally extended multi-regional input-output tables (EE MRIOs). Pymrio aims to provide a high-level abstraction layer for global EE MRIO databases in order to simplify common EE MRIO data tasks. Pymrio includes automatic download functions and parsers for available EE MRIO databases like [EXIOBASE](http://www.exiobase.eu/), [WIOD](http://www.wiod.org/home) and [EORA26](http://www.worldmrio.com/simplified/).

Pymrio appears to be a Python command line utility.  Thorough documentation and some tutorials are at https://pymrio.readthedocs.io/en/latest/

That's as far as I've gone in looking into this today.  I don't have time to learn the Pymrio command line program today, so this is something we can return to in the future.

**Comment by robbieorvis** [comment]
Just want to add that we now have all this data for the IO model, which we compiled for the consultants working on those models. So at some point if we want to build this out in a lot more detail we have the data for all countries.

**Comment by jrissman** [comment]
The upgrade of the OECD economic data (discussed in issue #207) makes the prospect of moving to a different source like the EXIO database less appealing, but EXIO might still be useful in certain circumstances, particularly for countries that are not included in the OECD's database.

**Comment by jrissman** [comment]
With the expanded coverage of ISIC codes in the latest OECD data, we are closing this.  We might use EXIO to help do ISIC code splits but are unlikely to move to EXIO wholesale.
