### ISSUE TITLE
Formula error in BAU Hydrogen Sector Peak Hour Electricity Demand by Season

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#134]
Today I found a bug that was causing small policy effects in the BAU case. The variable BAU Hydrogen Sector Peak Hour Electricity Demand by Season multiplies the hydrogen sector hourly electricity demand by "ELF Equipment Load Factors by Sector[industry sector,Season]" while the variable Hydrogen Sector Peak Hour Electricity Demand by Season multiplies the hydrogen sector hourly electricity demand by "ELF Equipment Load Factors by Sector[district heat and hydrogen sector,Season]"

For now, since Robbie and I are working on a scenario and want to see the correct results as we go, I pushed a change fixing this in just the .mdl file in commit edd40f (I switched the ELF subscript in the BAU version of the variable to also use the district heat and hydrogen sector). Jeff, please advise how you'd like us to handle small obvious fixes like this in the future now that you are spending less time on EPS.

**Comment by jrissman** [comment]
I think the approach you've done here is good, where you (1) open a GitHub issue for the bug with version label, (2) explain the bug, and the fix you made, and (3) assign the issue to me.  This gives me a chance to confirm that the identified issue is in fact a bug and review the fix at my next opportunity, but it does not delay you from making the fix right away.  Or you can opt simply to open the issue and let me get to it next Thursday, if you prefer.

**Comment by jrissman** [comment]
Thanks for catching this bug.  This was introduced when I fixed #128 in the policy case but forgot to make the same update in the BAU case.

I confirmed your fix and updated EPS.vpmx (and EPS.mdl with starting on the overview sheet with the output CO2e variable selected).
