### ISSUE TITLE
Identified bug in industrial fuel shifting calcs

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#137]
I believe I've caught a bug in the industrial fuel shifting calculations. You can see in the screenshot of the "Increases in Industrial Fuel Use from Fuel Shifting" calculations below, the RIFF subscripts specify "cement and other carbonates" rather than "Industry Category." The RIFF values vary quite a bit between industry categories, so this would significantly affect our 1.5 results. 

![image](https://user-images.githubusercontent.com/56732097/104252689-721ea200-5427-11eb-9787-15f4457c1a98.png)

We're working on an important meeting to present the 1.5 results this week. Jeff - would it be possible to confirm this is a bug sooner than Thursday so we can confirm our values?

**Comment by jrissman** [comment]
I looked at it in Vensim (going back to the first version that introduced this calculation 2.0.0).  It does appear to be a bug, and your fix of changing it to "Industry Category" appears to me to be the correct fix (though I haven't tested that fix myself).

**Comment by mkmahajan** [comment]
Thanks, Jeff. I made the fix and it appears to be working as intended - we end up with more hydrogen and less industrial electricity use in the 1.5 scenario. I pushed a change to the .mdl file for now.

**Comment by jrissman** [comment]
The fix looks good.  I added it to the .vpmx file in the latest commit.  Closing this issue.
