### ISSUE TITLE
Fix Categorization of Methane Abatement in PERAC

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#144]
The IEA methane data in PERAC is not correctly categorized into the three buckets (production, processing, and T&D).  This has little effect on EPS versions before 3.2 because the abatement potential was applied against a lumped “natural gas and petroleum systems” industry.  However, EPS 3.2 breaks up this NGPS industry into two industries – “oil and gas extraction” (which matches the “production” bucket you use in PERAC) and “energy pipelines and gas processing” (which contains the sum of the other two buckets you use in PERAC).  The abatement potential from IEA allocated to the “production” bucket is just 40% of the oil and gas extraction methane process emissions in 2050.  Meanwhile, the abatement potential allocated to the “processing” and “T&D” buckets together is equal to 172% of the methane leakage in 2050 – this value should not go about 100%.

The bucket assignments appear to be on the **"IEA Tech to Policy Mapping”** tab for IEA, which is the dataset we’re using now for the U.S.

The total abatement potential across all three buckets is about 71% of the 2050 methane emissions, which seems about right, and matches the pre-3.2 guidance text.  So I don’t think the magnitudes of any of these numbers is wrong – it may just be that you need to update the technical-measure-to-bucket mapping to put more technical measures into the “production” bucket and fewer into the “processing” or “T&D” buckets.

Then, you’ll then need to update the guidance text in WebAppData to specify whatever these two percentages are after you adjust the assignment of these technical measures.

I would recommend checking the EPA methane abatement potential in 2050 (in PERAC) against 2050 methane process emissions from "oil and gas extraction" and from "energy pipelines and gas processing" in BPEiC to make sure there isn't a problem with the tech-to-bucket mapping there similar to the issue with the IEA mapping.  If there is, you might want to update the EPA tech-to-policy mapping at the same time as you update the IEA mapping.

**Comment by mkmahajan** [comment]
Done in commit bc36b6
