### ISSUE TITLE
Adjust indst fuel shift target fuel settings in 1.5-degree scenario

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#146]
In EPS 3.2, it is now possible to specify separately the extent to which each industry shifts to electricity and shifts to hydrogen (per issue #116).  This policy is used in the 1.5-degree scenario.  I've set the levers to 50% electricity, 50% hydrogen for all industries, based on the average overall heat demand at different temperature ranges (see the guidance text I wrote for this lever).  If you want to, you can improve on this by selecting different settings for different industries - for instance, more hydrogen for the steel industry, more electricity for the textiles and apparel industry.  The lever settings should still sum to 100% (or less).

This is not an input data matter - this is for the lever settings for the policy scenario.

**Comment by mkmahajan** [comment]
Thanks for this, @jrissman! Based on your industry sector work, do you have any suggestions for potential data sources if we wanted to tailor this by subindustry? I know it's challenging to find good data on this, so any insights you have would be appreciated. I know we tried to get at this in the previous RIFF file, but the source data for that approach didn't have the kind of detail we'd ideally want.

**Comment by jrissman** [comment]
Well, the way I'd recommend doing it is based on temperature ranges for the demanded heat.  In [this study](http://www.inship.eu/docs/sh9.pdf) on page 5 (page 9 of the PDF), they have some heat demand temperature ranges broken out by industry.

![Temps1](https://user-images.githubusercontent.com/7120106/108275706-97d84e80-712b-11eb-8c09-564f65e13737.PNG)

![Temps2](https://user-images.githubusercontent.com/7120106/108275717-9a3aa880-712b-11eb-915c-1a3fc4d199cd.PNG)

For instance, in the two figures above, I'd probably assume the yellow and bright green ranges (<100 and <160 C) are met entirely with electricity.  The orange range (100-400 C) is tough, maybe a 75-25 mix favoring electricity, because hydrogen is still a new technology and is likely to mostly be reserved for the highest temperatures for a long time.  You might assume the red range (>400 C) is met with hydrogen.

These figures don't include every industry in the EPS 3.2, but maybe you can use these as a guide and pick the most similar industry, or average the two most-similar industries, for one where we don't have explicit temperature demand data.

**Comment by mkmahajan** [comment]
Thanks! These figures are very helpful.

**Comment by jrissman** [comment]
There's another document with a similar calculation [here](https://ec.europa.eu/energy/sites/ener/files/documents/mapping-hc-final_report_wp1.pdf) on page 93.  It's a little hard to read with precision, but it could be cross-checked against other sources.

![TempLevels](https://user-images.githubusercontent.com/7120106/109890964-14475300-7c3d-11eb-9cb7-87bcc6998737.PNG)

**Comment by jrissman** [comment]
I've been looking into various data sources for heat demand at different temperatures today.  Based on this lit review, I'd recommend using the second document I posted here (the one with data for the EU28 in 2012) rather than the earlier document (with data for Europe from 2003).  The latter one is from the Fraunhofer Institute, a respected organization, and it contains the most recent data I've found on heat demand by temperature range for a large geographic area.  In the Fraunhofer PDF, the figure was provided as a vector image, so I was able to use a vector art program report the bar component heights (i.e. without having to measure pixels, to avoid introducing measurement error).  I then converted the values from TWh to PJ.  I've made the table below that contains the values.

Note that the rows in my table below are not in the same order as the columns in the figure above.  If you ignore the figure above and just use this table, you'll be fine.

### Heat Demand by Temperature Range by Industry in the EU28 in 2012 (PJ)
Industry | >500 °C | 200-500 °C | 100-200 °C | <100 °C
-- | -- | -- | -- | --
Iron & Steel | 1752 | 56 | 0 | 56
Nonmetallic Minerals | 855 | 168 | 112 | 28
Chemicals | 896 | 28 | 140 | 281
Nonferrous Metals | 84 | 56 | 15 | 28
Food & Beverage | 41 | 56 | 209 | 211
Pulp & Paper | 13 | 43 | 714 | 97
Machinery & Vehicles | 0 | 28 | 99 | 41
Other Industries | 0 | 196 | 518 | 84

**Comment by robbieorvis** [comment]
Thanks, Jeff. Megan, I’ve added this to Monday as a follow-up.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D710E0.5F7EC060]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by mkmahajan** [comment]
Done in commit 49903f.
