### ISSUE TITLE
Bug fix for biofuel/biomass in Direct Change in Fuel Industry Revenue by ISIC Code

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#147]
Changes in biomass and biofuel supplier revenue should be mapped to ISIC 19 rather than ISIC 01T03.

**Comment by jrissman** [comment]
Just noting for records in this thread that only the liquid biofuels should be remapped to ISIC 19, while biomass (e.g. wood and agricultural residues) should remain mapped to ISIC 01T03.

**Comment by mkmahajan** [comment]
Closed in commit 1b91b9
