### ISSUE TITLE
Bug in variable Change in Fuel Use by Fuel and Technology due to LCFS with Elec Eff Adj

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#152]
In the variable Change in Fuel Use by Fuel and Technology due to LCFS with Elec Eff Adj, increases in biodiesel for aircraft result in a change in petroleum diesel rather than jet fuel. That leads to negative petroleum diesel consumption and no change in jet fuel consumption. I implemented a fix for this in the .mdl file on the develop branch. @jrissman would you like to review when you have a chance?

**Comment by jrissman** [comment]
I reviewed your fix.  It looks nicely-done.  I had no changes or corrections to make.  I published a .vpmx to match the updated .mdl file and pushed it to the repo.
