### ISSUE TITLE
Add wedge diagram calculation description to docs

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#157]
We should add a new documentation page explaining how we calculate the wedge diagrams. Have gotten multiple requests for this information.

**Comment by jrissman** [comment]
In fact, we do have two doc pages that link to the procedure (which is described in a GitHub thread).  The doc pages containing these links are:

- https://us.energypolicy.solutions/docs/how-the-eps-avoids-double-counting.html
- https://us.energypolicy.solutions/docs/web-interface-graphs.html

We also have one outdated doc page which references an older procedure:

- https://us.energypolicy.solutions/docs/testing-policy-contributions.html

I do think it is worthwhile for me to make a page to describe the wedge diagram and cost curve procedure, borrowing from the text in the relevant GitHub thread, and then to update all three of the pages above to refer to that new page.

**Comment by robbieorvis** [comment]
Thanks. Yes I have shared those around but they don’t explain the procedure in detail, which is what several folks have asked about.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D73790.83DBD700]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Completed in f036021.
