### ISSUE TITLE
Update bldgs/RBFF to exclude biomass burning from electrification

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#158]
Currently the model shifts all sources of energy combustion to electric, but it is unlikely that electrification policies would target wood burning given that it is CO2-neutral. We should update the input data to reflect this. It's also important because wood burning is responsible for the majority of building related premature mortality, and including electrification of wood burning sources in our modeling gives the impression of too high of avoided premature mortality from building electrification.

Note that after playing with this, I noticed that we can't have all zeroes for a fuel category in RBFF, so the way to handle this is to set the biomass-biomass cell to 1 and set the rest to 0.

**Comment by oashmoore** [comment]
pushed to develop
