### ISSUE TITLE
Allow different policy schedules for each subscript of each subscripted policy

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#16]
Allow different policy schedules for each subscript of each subscripted policy.

Note that this would require a large expansion of the policy schedule input data variables (FoPITY), would increase the memory footprint of the model non-trivially (i.e. might break Vensim 7 compatibility), and would require corresponding work on the web app to support this feature in the web interface.  It would also make it more annoying to set the schedules for highly disaggregated policies in the web interface, as a user would have to repeat the necessary schedule change on every affected subscripted element.  Perhaps this feature should be on hold unless/until we develop a UI element that allows a web app user to set the properties for all subscripted elements of a particular policy lever at once (e.g. by mirroring the schedule across elements, and by setting all subscripted elements' levers to the same percentage of their maximum values).

**Comment by jrissman** [comment]
This is done on the Vensim side.  The model now uses a separate implementation schedule for every element of every policy, rather than a single schedule for every policy.  I'll need to hand this off to Todd so he can build web app support for it.

I updated the policy schedules for the included reference scenarios to mirror the values they had previously, now applied to every element within each policy.

@mkmahajan @robbieorvis @oashmoore - Do you want to update the Net Zero or NDC schedules to take advantage of this new capability and use different policy schedules for different elements of the same policy?

**Comment by jrissman** [comment]
Oh, I forgot to mention that I've added the capability for the GRA levers to use implementation schedules as part of my work on this issue.  So now, for example, you can have a subsidy that begins by being funded through deficit spending and gradually transitions to being funded some other way, or you can have a tax that is at first rebated to households, and gradually changes such that the government uses the revenue some other way, etc.

**Comment by robbieorvis** [comment]
Sure, once Todd has a timeline or completes the web app side, I'll updated accordingly.

**Comment by jrissman** [comment]
Since the final U.S. EPS 3.1 was delivered by Robbie today, we assume it includes any desired schedule updates to use this new feature, so it is time to close this issue.
