### ISSUE TITLE
Make BAU Output by ISIC Code a time series variable

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#163]
Several data sources have output by ISIC code in future years, including for the US and EU models. We discussed adding in the structure to correctly handle this data. Full discussion below:

Hi Jeff,

Thanks for this and thinking through this. You definitely bring up a lot of things I hadn’t considered!

Some of the datasets may have the value added component, but they almost certainly don’t have the other components you mention, so we would have to scale.

I also realized that to complicate things further, we have projected labor productivity rates for each sector as well, and that would also have to be factored in, meaning it may not be as simple as scaling value added and holding the percent of labor constant (we could rescale the percent of labor, but the question is then what do the industries do with the reduced value add spending? Do they drop prices? Do they hold prices constant but increase profit? Etc…). It’s definitely tricky!

I would be open to thinking through it some more though. Perhaps we can spend some of our check-in tomorrow thinking about how this might work.

There are a couple of reasons I brought this topic up (in addition to improving accuracy): in the EMF working group, one of the sets of outputs they are asking for is projected future output by industry, so that leads me to believe that many models have this data, though my guess is that they have it to estimate energy demand, with an energy intensity multiplier, and not that they are trying to estimate employment; another is that I have been asked specifics about outputs from different industries in future years but currently don’t feel confident answer that because we are really only estimating the change from some future year and not the total output since we are holding today’s output constant.

Anyway, looking forward to discussing more!

-R

________________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org
 
________________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy
Available wherever books are sold

 

From: Jeffrey Rissman <jeff@energyinnovation.org> 
Sent: Wednesday, May 19, 2021 1:09 PM
To: Robbie Orvis <robbie@energyinnovation.org>
Subject: RE: Should BAU Output by ISIC Code be time series?

Hi Robbie,

Do the BAU data you’re talking about capture shifts in the percentage of output from different ISIC codes?  For instance, do they show ISIC 05 (coal extraction) having a smaller share of total output in future years than ISIC 05 has today?

Do you have similar data for the other variables we use along with output?  For instance, BAU Value Added, BAU Employment, and BAU Employee Compensation?  These values would get out-of-sync if you update BAU Output but fail to update those others.  For instance, it would show that coal output drops, but somehow coal’s value added, employment, and employee compensation remain the same.

If you don’t have data for those three, we could scale them all to match the changes in output in percentage terms.  But that’s harder to do with DLIM and TLIM.  For instance, suppose your data show ISIC 20 (chemicals) grows in future years.  We can assume employment, value added, and employee compensation grow proportionately.  But for DLIM and TLIM, who buys those new chemicals?  We could assume it’s all the same buyers as we have today, but scaled up proportionately, but that wouldn’t do.  I think the thing to do would be to first scale the columns (the buyer industries) according to changes in BObIC, and then scale the rows (the seller industries) according to changes in BObIC.  We’d have to see if it works.  (I can do the scaling inside Vensim so that we don’t have to split DLIM and TLIM into dozens of different CSV files.  This would be much cleaner than trying to do it in Excel.  For that matter, I could similarly do the scaling of BAU jobs, value added, and EE compensation in Vensim, rather than requiring those variables to be supplied as time-series, minimizing the increase in difficulty of obtaining input data across the various EPS regions.)

I do think this is doable if you have BAU data on output by ISIC code that shows the output of each ISIC Code in each future year (and is intelligent about it – i.e. it’s not just blindly scaling up all industries’ outputs by the overall change in national GDP).  It is worth doing.

But you should be aware this is not as quick an update as your message seems to imply, because it requires the whole suite of I/O variables to be updated together, so they remain in-sync.  Just updating output without touching the others would get things out-of-sync and break stuff.  But I think the others can be estimated inside Vensim rather than scaled in Excel if you don’t have explicit projections, and this might be better anyway, because it ensures that they remain in-sync (whereas using different input data files means there is a risk that the different data sources don’t line up, and if that happens, you can get runaway behavior in the energy use feedback loops that is very difficult to debug).

Jeff

From: Robbie Orvis <robbie@energyinnovation.org> 
Sent: Wednesday, May 19, 2021 6:19 AM
To: Jeffrey Rissman <jeff@energyinnovation.org>
Subject: Should BAU Output by ISIC Code be time series?

Hey Jeff,

Quick question for you. I noticed that BAU Output by ISIC Code is a time invariant input file, but I am wondering if it should be a time series file? With the new data we are using in the US from EIA, we have output as a time series by industry. Other data sets, like the one we are using for the EU, also have this as a time series. I think that the decision to make it time invariant was that the OECD data is for a single year, but we could also format the file as a time series and use static data for regions without projections. What do you think?

**Comment by jrissman** [comment]
I'm upping this one to "high priority" because I think it is important and structurally tractable.

Let me know if you are able to provide a time-series version of io-model/BObIC (the Excel file).  It should not just scale every ISIC code up or down in proportion to future GDP changes, but rather, it should show which ISIC codes are likely to grow or shrink over time in the BAU case.  For instance, coal mining should get smaller over time even though total GDP increases.  If you can supply that Excel file, I think I can adjust all the rest of the IO variables structurally within Vensim to enable time-series performance across all IO variables, even the DLIM/TLIM matrices.

**Comment by robbieorvis** [comment]
We should be able to supply this, but also if you wanted to get started before then, the AEO tables with the industrial energy consumption by industry have a Value of Shipments output, which is the same as the value output.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D75882.AFF8CD30]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Actually, one other variable we could potentially choose to supply by time-series is `BDCSoCbIC BAU Domestic Content Share of Consumption by ISIC Code`.  How the balance between domestic production and imports changes over time in the BAU case can't be deduced from changes in output.  (But if we stick with time-invariant values in that variable, that's not too bad.)

**Comment by robbieorvis** [comment]
Yeah, the only issue is that with that one I have no idea where to find data, whereas with BAU Output it often exists in other models.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D75892.4902F8C0]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Knowing that the AEO has time-series data on output from each industry they track is great.  However, this only covers about half of the ISIC codes.  We also need time-series data on change in output from the ISIC codes that are not EPS industry categories, such as those pertaining to banking, real estate, education, government, transportation and warehousing, etc.

I could of course scale the present-day values up by our GDP projection data (which is already in the EPS).  However, the point of this feature is to understand how the economy shifts over time in the BAU case, which depends on the ratio of one ISIC code to other ISIC codes.  If they all scale up proportionately, that's already how we do it in the model today, so the new feature wouldn't be adding anything (for these specific ISIC codes).  So it would be preferable to find a source with time-series projections of output for all ISIC codes, not just the industry categories.

If that's impossible, the next-best-thing is probably along these lines:
* Use AEO data to project forward all the ISIC codes they support
* Note how much this results in growth of GDP
* Subtract this from the GDP projection to find the remaining growth (attributable to the ISIC codes not in AEO)
* Scale forward all the non-AEO ISIC codes to achieve this remaining growth (so total growth across AEO and non-AEO ISIC codes matches the overall GDP growth projection)

This would not change the ratios of the non-AEO ISIC codes with respect to each other, but at least it would keep them balanced against the AEO ISIC codes and would ensure the overall total equals the GDP growth projection.

Before I do it that way, I want to give the other EPS team members some time to look for or propose a data source other than AEO that might provide output projections for more ISIC codes.

**Comment by jrissman** [comment]
Note that GDP is a sum of value added, not a sum of output, so some conversion might be required.

**Comment by robbieorvis** [comment]
Okay, here’s one starting point, with 10 years of projections:

BLS has projections here: https://www.bls.gov/emp/tables/output-by-major-industry-sector.htm

There’s additional detail here: https://data.bls.gov/projections/occupationProj



________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA 94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D76F56.DB19A300]

**Comment by jrissman** [comment]
Thanks for these.  The first link is the sort of thing we're looking for, but the industry categories are more aggregated than is ideal.  The second link isn't what we're looking for because it is by job role, not by industry, and they can't be mapped one onto the other.  (A given industry contains many job roles, and a given job role occurs in many industries.)

Fortunately, BLS does have a table with projections by industry that has a fine-grained breakout of industries (Table 2.7):
https://www.bls.gov/emp/tables/industry-employment-and-output.htm

The only flaw with (all) BLS data is it only goes out to 2029, but I've looked online at some other places (BEA, CBO, Federal Reserve) and can't find any granular projections better than the BLS ones.  So I'm going to go with the BLS table 2.7 (for ISIC codes not included in the EIA Annual Energy Outlook).

**Comment by jrissman** [comment]
Completed in commits 0ad1ad5 and 841e855.
