### ISSUE TITLE
Emissions from imported electricity currently counted in health impacts

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#165]
I noticed that for the Oregon EPS, which includes emissions from imported electricity, those emissions count toward the health impact calculations. I think we want to subtract out the emissions from imported electricity before we calculate the health impacts. For example, Oregon has a lot of coal imports from Wyoming. But a policy to target those emissions wouldn't likely save many lives in Oregon. 

I'm happy to make a Vensim edit for this.

**Comment by jrissman** [comment]
Okay, but let me ask, is a policymaker who cares about emissions in other regions so much that he/she wants to see those emissions blended into the in-region emissions totals also the sort of policymaker who cares about lives saved in those regions?  Would it be misleading for large reductions in particulate emissions to show few lives saved because those lives were being omitted in the first place?  For instance, if Wyoming burns lots of coal and Oregon does not, all of the lives saved from reducing coal use might be in Wyoming, so a policy that reduces coal emissions would not appear to save any lives.  Is that the desired behavior?

**Comment by mkmahajan** [comment]
That's a good point. On the other hand, we often present the jobs and health numbers side-by-side. Since the jobs numbers only report in-state impacts, I'm afraid that may be misleading. I'm not sure what the correct answer is here, but the avoided deaths from reducing coal imports is more than half of the total in OR's NDC scenario, so it can have quite a big impact. @robbieorvis - thoughts?

**Comment by robbieorvis** [comment]
We don’t want to include avoided premature mortality from out of state emissions, even if those emission are included in GHG inventories, so I suggest the original request to remove them (and perhaps make it clearer somewhere we only look at in-region emissions).

For the most part, including imported emissions is only done for the power sector and is somewhat of an accounting trick for states to control the desire for utilities to simply escape in-region regulation by contracting outside the state.

I’ve never heard of a state including other states’ emissions in it’s regulatory assessment of health co-benefits, so I think the desired approach here is to exclude those.

We also don’t have any sophisticated modeling for imported electricity which makes the results less robust, and I would be worried if a simple fixed assumption about imports were driving a significant share of health benefits (while the same holds true for GHG emissions, the impact as a share of total emissions is less than it would be for health impacts).

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D7507D.BD410CD0]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Okay, will not count health impacts of emissions associated with imported electricity when the setting to "Include Emissions from Imported Electricity" is enabled.

**Comment by jrissman** [comment]
Completed in 871efb4
