### ISSUE TITLE
Add losses percentage for district heating

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#170]
District heat supply should have a loss percentage associated with it like electricity supply does.

**Comment by jrissman** [comment]
Good idea.

Here are some papers with data on district heating loss percentages in the transmission and distribution network:
https://www.sciencedirect.com/science/article/pii/S1876610216307081
https://www.sciencedirect.com/science/article/abs/pii/S1359431103003648?via%3Dihub
https://www.diva-portal.org/smash/get/diva2:1008413/FULLTEXT01.pdf

Looks like 10-20% is fairly typical, though it varies quite a bit by system.

**Comment by robbieorvis** [comment]
Great. We have data from our main EU model data source, POTENCIA, for the EU model, but am happy to use any of these sources as a default.

________________________________
Robbie Orvis
Director of Energy Policy Design
+1 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA 94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D768E9.57B41F90]

**Comment by jrissman** [comment]
Completed in 694e0aa
