### ISSUE TITLE
Correct data issue with BPoEFUbVT for ethanol

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#171]
During a recent data update the methodology was incorrectly modified for calculating the share of gasoline that is ethanol. EIA's data has an E85 category, which is being used to represent this value, but the vast majority of ethanol consumed is in blended motor gasoline, where ethanol makes up roughly 10% of gasoline. See here for more info: https://www.eia.gov/energyexplained/biofuels/use-of-ethanol-in-depth.php

This is an easy fix but has very important implications for the national and state models and especially when using the LCFS policy.

**Comment by oashmoore** [comment]
Pushed an update, values held constant through 2050. The states have a custom file (with ethanol about 7%)

**Comment by robbieorvis** [comment]
And now that I'm seeing this, I think there is an issue with the Max amount for ethanol also. Non flex-fuel vehicles can only really use up to 15% ethanol, not 25% as is currently set. This is commonly referred to as the "blend-wall." Per the previously linked EIA document, EPA recently ruled that the blend wall could be raised to 15% (from 10%) for vehicles produced after 2001, which would be most of the cars in the US fleet and that currently blending is right about at the 10% value.

**Comment by oashmoore** [comment]
just pushed updated max biofuels file!
