### ISSUE TITLE
Update public health doc page with demographic breakout details

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#172]
Update the doc page at 
https://us.energypolicy.solutions/docs/additional-outputs.html
with the new structure for demographic breakouts of health impacts.

As with all structural doc pages, this only covers the Vensim components.  The steps done in the Excel file should be documented within the Excel file itself.  (I can update the "About" tab with the more detailed write-up I recently sent by email.)

**Comment by robbieorvis** [comment]
Perfect – thanks!

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA 94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D76E89.9F3F4E20]

From: Jeff Rissman ***@***.***>
Sent: Thursday, July 1, 2021 2:54 PM
To: Energy-Innovation/eps-us ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Energy-Innovation/eps-us] Update public health doc page with demographic breakout details (#172)


Update the doc page at
https://us.energypolicy.solutions/docs/additional-outputs.html
with the new structure for demographic breakouts of health impacts.

As with all structural doc pages, this only covers the Vensim components. The steps done in the Excel file should be documented within the Excel file itself. (I can update the "About" tab with the more detailed write-up I recently sent by email.)

**Comment by jrissman** [comment]
Completed in 0e75ecf
