### ISSUE TITLE
Assign Aluminum-making F-gas Emissions and Abatement to Other Metals industry, not Chemicals industry

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#178]
The EPS currently assigns all F-gas emissions (and abatement potential) to the Chemicals industry, because the Chemicals industry produces (almost) all the F-gases, even the F-gases purchased and used by other industries (such as PV and semiconductor manufacturing).  However, there is one industry other than the chemicals industry that produces F-gases: the aluminum industry.  F-gases are a byproduct of aluminum manufacturing.  

Both the BAU process emissions of F-gases and the potential abatement of F-gases for the aluminum industry are currently assigned to the Chemicals industry.  Therefore, the EPS currently reports the correct total quantity of F-gas emissions and the correct total abatement (and costs), but some of those emissions and abatement ought to be assigned to the "other metals 242" industry rather than to the chemicals industry.

The amount of F-gas emissions from Aluminum is small (around 1% of total F-gas emissions in the U.S.), so this won't change the results very much, but it may be of value to someone who is interested in how to decarbonize the aluminum industry in particular.

To do this requires the following changes:

1. In `indst/BPE`, on the "EPA Source to Industry Map" tab, assign the emissions with subsource "Aluminum" to the `other metals 242` EPS industry category
2. In `indst/BPE`, on the "Multipliers and Adjustments" tab, create a new row with multipliers for the `other metals 242` industry in both of the tables of multipliers (5-year increments and annual increments).  The multipliers should all be 1.
3. In `indst/PERAC`, add a row of multipliers to the "Multipliers and Adjustments" tab for the `other metals 242` industry
4. In `indst/PERAC`, on the "EPA Tech to Policy Mapping" tab, assign the two rows with source "AL" to a new policy lever name, perhaps `other metals - F-gas inspection maintenance retrofitting`.  Also, rename the existing F-gas inspection/maintenance/retrofitting lever to `chemicals - F-gas inspection maintenance retrofitting`.  Add a new output tab for the new policy.  Make other updates as needed to get this spreadsheet working with the additional policy.
5. Subscript the F-gas inspection/maintenance/retrofitting policy lever by Industry Category.  This requires changes in `EPS.mdl`, `FoPITY`, `WebAppData.xlsx`, etc.  Make all necessary updates to get the new lever working.

This is low priority because the only thing it will do is to shift about 1% of the F-gas emissions (and abatement potential) from the chemicals industry to the other metals industry.  But it would still be worth doing sometime in order to have maximum accuracy when we report which industries are responsible for which types of emissions or abatement activities.

**Comment by jrissman** [comment]
My impression was that only chemicals and aluminum industries create F-gases, while electronics is a buyer of F-gases.  We haven't been assigning F-gas emissions to their buyers before.  There are other buyers of F-gases besides the electronics industry, such as the electric power transmission industry, which buys SF6 as a gaseous insulator.  That's why this issue only mentions breaking out aluminum, rather than aluminum and electronics.

Are you proposing we start assigning emissions from F-gases to the buyers of those F-gases rather than the producer?  Given that the most important F-gas abatement measure, particularly in the long term, is the use of less-harmful substitutes, and it is the chemicals industry's job to research new chemicals, I thought it felt like a natural fit to target the levers at the chemicals industry (except for Aluminum).  Admittedly, this is less suitable for F-gas destruction, which would have to be carried out by the purchasing industry, not by the chemicals industry.  But we have to assign the purchased F-gases to one industry or the other, so the fact that the levers imply measures to be undertaken partially by the F-gas supplier and partially by the F-gas buyer is slightly awkward.

**Comment by jrissman** [comment]
Or are you happy just breaking out Aluminum (and adding a new lever to target Aluminum)?  That was the original scope of this issue.

**Comment by jrissman** [comment]
I forgot that the majority of F-gases are purchased by everyday consumers (in refrigerators and air conditioners, including vehicle air conditioners) and a large number of small businesses, such as restaurants and convenience stores.  It would not be practical to add F-gas pollutants to the Buildings and Transportation sectors.  And the four F-gas levers don't really make much sense applied to individuals or even small businesses.

We could assign the emissions to the industries that make refrigerators, cars, etc., but those industries just pass along the F-gases, in the same way the Chemicals industry does.  They aren't able to either research new substitutes, nor to destroy the F-gases at end of life.  So applying the levers to them doesn't make sense either.

So I don't think assigning purchased F-gases to their buyers is something we want to do.  There doesn't seem to me to be any justification for breaking out the electronics industry, which is actually just a minor buyer.  I am leaning toward only breaking out Aluminum, since they are an F-gas producer with their own mitigation techniques and the responsibility to employ those techniques.

**Comment by mkmahajan** [comment]
Thanks for laying out this reasoning. I think breaking out only aluminum makes sense. @robbieorvis does that sound good to you?

**Comment by robbieorvis** [comment]
I hadn’t realized that HFC emissions outside of the use of ODS substitutes for ODS refrigeration is primarily from consumption and use. I thought it was a byproduct of industrial processes. Still, using HFCs for industrial processes is different than putting it into a (mostly) closed loop appliance.

So a couple of thoughts: First, I haven’t summed everything on the cost curves, but the mitigation costs and potentials vary by industry. For example, the semiconductor industry can do some substitution but also some destruction.

With this request I was thinking beyond the US, to China, for example, which has a massive semiconductor industry, and also thinking about the knock-on implications through the IO model, now that we have that.

All that said, looking at the EPA non-CO2 data, the emissions are quite small. All electronic equipment manufacturing is about 50 MMT from F-gases, out of about 250 or so total. Thought it would technically be more accurate to assign the emissions and PERAC to the appropriate industries, it probably isn’t worth the effort. And as you note, the allocation is a bit confusing since it is still consumption based and that also presents some challenges.

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
1225 Eye Street, N.W.
Suite 904
Washington, D.C. 20005
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***

**Comment by jrissman** [comment]
That's right, the only industries I know of that create F-gases are the chemicals industry and the aluminum industry.

The electronics industry purchases F-gases from the chemicals industry and uses them for plasma etching and cleaning of chemical vapor deposition chambers.

You are right that the semiconductor, photovoltaic, and flat panel display manufacturing industries are responsible for roughly 50 Mt CO2e of F-gases (more exactly, the figure was 56 Mt CO2e in 2018).  But total F-gases are quite a bit more than 250 Mt CO2e.  In 2018, the total was 1,136 Mt CO2e.  Here is the global breakdown of F-gas emissions (data for year 2018, from the [EPA non-CO2 GHGs report](https://www.epa.gov/global-mitigation-non-co2-greenhouse-gases/global-non-co2-greenhouse-gas-emission-projections)):

* Aluminum industry production: 36 Mt CO23 total (all of which consisted of PFCs)
* Chemicals industry production: 1100 Mt CO2e total, of which:
  * 979 Mt HFCs
    * 725 MT used as a refrigerant (refrigerators, freezers, air conditioners, etc.)
    * 95 Mt as aerosol propellant and foam blowing agent
    * 21 Mt as fire suppression chemicals
    * 7 Mt for cleaning solvents
    * 2 Mt for semiconductor and flat panel display manufacturing
    * 129 Mt are unwanted byproducts of producing other F-gases (primarily HCFC-22) for sale
  * 93 Mt SF6
    * 62 Mt high-voltage electrical insulator
    * 26 Mt for semiconductor and flat panel display manufacturing
    * 5 Mt for magnesium casting
  * 19 Mt PFCs
    * all 19 Mt from photovoltaics, semiconductor, and flat panel display manufacturing
  * 9 Mt NF3
    * all 9 Mt used in photovoltaics, semiconductor, and flat panel display manufacturing

Of the F-gases made by the chemicals industry (1,100 Mt), all of it is sold commercially except the 129 Mt of HFCs that are an unwanted byproduct of producing other F-gases.

We may never choose to assign F-gases made by the chemicals industries to the various F-gas purchasers (industry and non-industry).  But if we someday do this, we should strive to do so consistently for all F-gas users, or at least, all industrial F-gas users.

**Comment by jrissman** [comment]
Do this issue at the same time as #201, which also involves extending PERAC.

**Comment by jrissman** [comment]
Megan,

Note that now that we subscript the ability to include/exclude each industry's process emissions from the carbon tax (see #183), this will need one more thing updated that we didn't used to need to update when we added the agricultural tillage policy.  The subscript "Industry Category" has a new sub-range called "industries with process emissions policies."  You'll need to add `other metals 242` to this sub-range in the correct position, i.e., corresponding to the position in which you put the new F-gas abatement policy in the `Industry by Process Emissions Policy` subscript.  This tells Vensim which industry corresponds with which entry in the `Industry by Process Emissions Policy` subscript, so it knows which ones to exclude/include based on the user setting.

Apart from that, the process will be relatively similar to what we did together when we added the agriculture tillage policy.  But since this isn't relating to CO2 process emissions, it won't need any special exception in the variable `Process Emissions Abated due to Carbon Tax by Marginal Cost` (like we had to put in for tillage).

I'd recommend blocking out more time than you expect to need for this GitHub issue, because it requires a number of steps and has some trickiness to it, and having time to carefully troubleshoot any issues you encounter can be helpful for learning.

**Comment by mkmahajan** [comment]
I believe this feature is now complete (data work is done and new structure tested in Vensim and web app). However, @jrissman and I should plan to review this feature together at our next joint session before I officially close this issue out.

**Comment by jrissman** [comment]
Looks great!  Thank you so much!
