### ISSUE TITLE
Add a fuel subsidy policy

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#182]
We've had more than one request for a fuel subsidy policy lever (India and the US). 

I'm also noting here that one potential use of this lever is to subsidize transportation biofuels as proposed in the Clean Energy for America Act. But currently, this would only affect cash flows and not emissions, since the share of biofuels in each vehicle is set through input data. Robbie and I discussed revisiting this when eventually rebuilding the LCFS policy.

**Comment by jrissman** [comment]
I seem to recall we've done this before by entering a negative number in the fuel tax policy lever.  That won't affect whether internal combustion engine vehicles buy petroleum gas or biofuels, but it will affect everything that is affected by fuel prices.  It does need retesting, though, to make sure it still works without violating any assumptions.

**Comment by robbieorvis** [comment]
Just confirming that yes, the negative tax works. @jrissman planning to use existing code but modify WebAppData

**Comment by jrissman** [comment]
Completed.  I renamed the lever not just in WebAppData but in a variety of places in the Web App code, and adjusted the bounds within Vensim as well.

**Comment by jrissman** [comment]
Sorry, when I said "Web App code," I meant "Vensim code."
