### ISSUE TITLE
Link percent change in production for the energy pipelines and gas processing industry to demand rather than natural gas production

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#194]
Currently, the Percent Change in Production due to Policies for energy pipelines and gas processing is linked to natural gas production. In a state like OR, which has little natural gas production, it's possible for natural gas production to reach 0 in the policy scenario due to falling gas demand. In that case, the Percent Change in Production for gas pipelines also becomes 0, even though there will still be gas transmission/distribution in the state. This creates a large discontinuity in the CH4 emissions. Instead, can we link the percent change in production for the energy pipelines/gas processing industry to demand? 

I've labeled this as 3.3.1 since it affects OR and we'd like to release that on the 3.3.1 platform soon, but hopefully this would be an easy fix.

**Comment by jrissman** [comment]
Completed in 990e8bc.  Note that for the U.S. NDC package, the percent reduction in demand for natural gas is -80%, but the percent reduction in production of the "energy pipelines and gas processing" industry is -50%.  So it's a pretty big difference.  Most methane leakage is at the wellhead, not in a transmission system.  I'd like to leave this open while we test this a bit.  I want to make sure that by solving a problem for regions without natural gas production, we aren't over-estimating the reduction for regions with natural gas production, especially if they are able to respond to cuts in NG demand by increasing NG exports.  @mkmahajan, can you review this fix and see if you think it still represents the U.S. national region well, and would represent a region that is capable of responding to cuts in NG demand by increasing NG exports?  We may need some logic in the model that, for example, moderates the change in NG demand by the change in NG exports before taking the percentage change.  But before I put something like that in, I want to see what you think of the current version.

**Comment by jrissman** [comment]
Okay, I looked at this again tonight and decided that omitting the change in NG exports is simply a mistake - there is no justification for it.  I went ahead and added the change in NG exports into the calculation in 292497c.  Now the variable is the reduction in "domestic plus exported demand" for natural gas, rather than the reduction in "domestic demand" for natural gas, which better reflects the use of the NG transmission system in places with the ability to compensate for NG demand reductions by increasing NG exports.  Now the reduction is -68% in 2050 for the NDC scenario, which is more than it used to be (it was -53%), but not as much as when we weren't accounting for exports (-80%).

**Comment by jrissman** [comment]
I'm feeling better about this one since fixing the exports issue, so I'm going to close it.  But I still think it is worth some testing.

**Comment by robbieorvis** [comment]
Hi Jeff, just want to clarify the methodology here. O&G emissions are split into oil and gas extraction and energy pipelines and gas processing. The new approach uses change in production to scale emissions from oil and gas extraction and changes in demand + change in exports to estimate changes in energy pipelines and gas processing, right?

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
1225 Eye Street, N.W.
Suite 904
Washington, D.C. 20005
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***

**Comment by jrissman** [comment]
Yes
