### ISSUE TITLE
Disaggregate industry electrification by temperature range

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#196]
Currently, the EPS has an industrial fuel shifting policy (for fuels used for energy purposes, not for feedstocks), which allows existing fuels to be shifted to any combination of other fuels.  In the U.S. model, it is set up as a lever that shifts specific industries to electricity and/or to hydrogen combustion, with those values set by the user (so the user can use the lever as electrification, as hydrogen, or as both in any combination).  There is a fixed efficiency gain for shifting to electricity specified in variable `PIFURfE Percentage Industry Fuel Use Reduction for Electricity` which is rather weak in the U.S. model (just 22% energy savings).

A more realistic approach to industrial electrification would involve using heat pumps to electrify all heat needs at temperatures heat pumps can efficiently deliver (roughly up to 165 C) and then to allow the user to specify a split between direct electrification and hydrogen combustion for higher temperatures.  The efficiency multiplier used for direct electrification of low-temperature heat should be based on heat pumps and therefore should be far better than the multiplier used for direct electrification of high-temperature heat.

Essentially, we'd be doing the following steps:
1. Add a new lever for electrification of low-temperature industrial heat.  This lever causes heat pump deployment and uses efficiency and capital costs based on industrial heat pumps.
2. Remove the energy demand for low-temperature industrial heat from the quantity that is shifted by the existing industrial fuel shifting policy.  Rename that policy to state that it only operates on medium- and high-temperature heat.
3. Review the efficiency value in variable `PIFURfE Percentage Industry Fuel Use Reduction for Electricity` to make sure it is appropriate for direct electrification of medium- and high-temperature heat.  22% seems rather modest even for these higher temperatures.  Rename it to indicate it is for medium- and high-temp heat.
4. Double check to make sure we don't need any changes to the industrial CCS code, which should only operate on the remaining CO2 emissions after all the electrification and hydrogen fuel switching are done.  It's probably fine with no changes, but just review it to make sure.

**Comment by mkmahajan** [comment]
I'm adding a note to this issue (though feel to break out into a separate issue) to consider disaggregating costs for electric and hydrogen fuel shifting in indst/CtIEPpUESoS. Currently, we use a single $/BTU value for all fuel type shifting.

**Comment by jrissman** [comment]
Programming on this issue is done.  It still needs at least two data updates:

1. Add a source for the relative reduction in energy use from electrification (due to higher efficiency of electricity to heat vs. fossil combustion to heat).  It currently uses placeholder data.
2. Add costs of heat pumps to CtIEPpUESoS.

Also consider whether to look for more data on temperature demand breakdown by industry (for IHDbT), but that is optional because the data in IHDbT might be good as is.
