### ISSUE TITLE
Data bug in hydgn/HPEbP

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#198]
There is a calculation error in this file. The calculated efficiencies add in BTUs lost in conversion as part of the input fuels, overstating the input fuel amount and therefore creating a lower efficiency than is realistic. Easy update that is being done in the analysis branch and can be brought over.

**Comment by robbieorvis** [comment]
See attached for file updates
[Hydgn Production Eff by Pathway.xlsx](https://github.com/Energy-Innovation/eps-us/files/7455898/Hydgn.Production.Eff.by.Pathway.xlsx)
[HPEbP.csv](https://github.com/Energy-Innovation/eps-us/files/7455899/HPEbP.csv)
.

**Comment by jrissman** [comment]
Megan reports this was fixed in 3.3.1
