### ISSUE TITLE
Use new EPA source for BAU process emissions, abatement potential, and costs

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#20]
Update to [this new EPA source](https://www.epa.gov/global-mitigation-non-co2-greenhouse-gases/global-non-co2-greenhouse-gas-emission-projections) for cost curves for non-CO2 GHGs (process emissions).  Consider increasing the number of industry sector policy levers, based on reasonable groupings of available technology options in the EPA source.  Decide on the best structural approach to get the data into the model (new cost tiers, XY pairs with cost and abatement potential, etc.).  Use the new EPA source data for both indst/BPEiC and indst/PERAC, produced by the same Excel sheet.  Ensure that both BPEiC and PERAC can be toggled to different countries by adjusting a single drop-down menu in Excel.

Include a methane leakage adjustment factor to correct EPA data that undercounts methane leakage (assuming the undercount affects this new EPA report), and determine if EPA undercounting is U.S.-specific or affects all countries in the new report.  (See Megan's email received 10/1/2019 and Jeff's reply for more on this.)

**Comment by jrissman** [comment]
We adjust EPA's methane leakage estimates using [this study](https://science.sciencemag.org/content/361/6398/186), which says that leakage was 60% higher than EPA's inventory.

Megan checked the new EPA report and confirmed that the U.S. methane emissions are in line with EPA's older GHG inventory, which means the new methane emissions figures need adjustment, at least for the U.S.  We are now working to determine whether to adjust all countries' methane leakage or just U.S. leakage in the new EPA report.

**Comment by jrissman** [comment]
We have decided that since the EPA is using separate data sources (often nationally reported) from each country, and the study finding the EPA was 60% low was particular to the U.S. inventory, we will not apply the 60% adjustment to other countries by default.  Instead, we will include a table or feature that allows the model adapter to customize the leakage rate adjustment (up or down) for the particular region being modeled.

**Comment by jrissman** [comment]
The new version will have the following policy lever changes:

- Drop "worker training" lever
- Combine "methane capture" and "methane destruction" levers
- Subscript "methane capture and destruction" lever by industry
- Combine "cropland management" and "rice cultivation measures" levers
- The "avoid F-gases" lever will continue to include some minor abatement of non-F-gas, non-methane emissions (e.g. N2O from nitric acid production), and this fact will be disclosed in the guidance text for the lever

The final set of policy levers will be:

- Avoid F-gases (& other non-methane emissions not covered by another lever), not subscripted
- Methane Capture & Destruction, subscripted by industry
- Cropland management and rice cultivation, not subscripted
- Livestock measures, not subscripted

Note that nothing here affects the cement clinker substitution lever, nor the shift to non-animal products lever, as those levers aren’t governed by the EPA MAC curves.

**Comment by jrissman** [comment]
I'm getting close to done building this.  Per our discussions, we have 13 levers (counting subscripted elements of each lever):

```
cement industry measures
ngps methane capture
ngps methane destruction
chemicals f gas substitution
chemicals f gas destruction
chemicals f gas recovery
chemicals inspct maint retrofit
coal mining methane capture
coal mining methane destruction
waste management methane capture
waste management methane destruction
agriculture crop and rice measures
agriculture livestock measures
```

Note that all the technologies assigned to the "inspct maint retrofit" category only abated F-gases, no other pollutants, so this is effectively a fourth F-gas policy lever.  We assign all F-gases to the chemicals industry, which produced them, not the sectors that use purchased F-gases.

The new PERAC file carefully builds a fully internationalized MAC curve for cement measures, of which clinker substitition is the only one right now.  Further measures, such as new cement chemistries, can be easily added to this curve in input data without structural edits.

We currently have a few types of process emissions that are not touched by any policies: process CO2 from NGPS, from iron & steel, from chemicals, and from other industries.  Also, the remaining CO2 from cement after clinker substitution can't be touched.  I'm thinking about putting in one more policy lever, something like "Hydrogen Feedstock Use," which could reduce process CO2 from iron & steel, chemicals, and the "other industries" category.  (Hydrogen use isn't relevent for cement process CO2, which comes from rocks- not methane- and I don't think the NGPS industry would switch to hydrogen when their purpose is to process fossil fuels.)  I'd need to add a linkage to increase hydrogen demand.  Process CO2 from iron & steel, chemicals, and other industries is pretty significant in the U.S. - this would be a pretty important lever.

**Comment by jrissman** [comment]
I've fully implemented this new feature in commits 868f911 and d8e831c, including the new internationalized data sources (for CO2 and non-CO2 process emissions, in both BPEiC and PERAC), all structural modifications necessary to use the new data, and associated updates to policy levers, reference scenarios (.cin files), WebAppData, and acronym-key.  I've done some light testing (ensuring each lever works) but haven't compared BAU process emissions, reductions, or costs between this version and eps-2.0.0-us.

The one thing I haven't done is update the WebAppData guidance text for the 13 new/changed levers (counting subscripted elements).  The guidance text doesn't require any outside sources or research - it just says that when fully implemented, this lever reduces process emissions from such-and-such industry (or from all industries, depending on the lever) by X% in 2050.  The methane capture and methane destruction levers' scopes changed, so they now need to be for specific industries instead the whole industry sector.  I think that updating the guidance text should only take about 20 minutes, and it should make for a good test of the new features.  I thought Megan might wish to do the guidance text updates and possibly other testing, so I'm handing this item off to you, Megan.  (However, if you don't have time or would rather not do it, just assign it back to me, and I'll do it.)

This is a big one - the biggest update coming in EPS 2.1.  Glad to have it done.

**Comment by jrissman** [comment]
I've noticed that this update breaks Vensim 7 compatibility, at least when running using the "Simulate" button (SyntheSim works).  It appears to be the same crash bug we observed when making eps-2.0.0, which I worked around through careful memory management techniques.  We reported this bug to Ventana Systems, and they fixed it in Vensim 8.  If we really care about continuing to maintain Vensim 7 compatibility for our users, I may be able to optimize the memory usage of the new feature and stay within Vensim 7's bounds, but I'm not sure that's a good use of my development hours.  Sooner or later, we'll just hit the same bug again.  The release of EPS 2.1 may be time to bump up the system requirements to Vensim 8.  (I've tested on Vensim 8.0.7 and it works there.)  I think our own DSS versions are in support, and our users generally use Model Reader, so they can get Vensim 8 with no payment.

**Comment by ssonniaa** [comment]
I agree it's not a good use of your development hours.

**Comment by robbieorvis** [comment]
Seconded. I think it's okay to lose Vensim 7 compatibility. We had this earlier with a 7.x release of Vensim, and decided it was worthwhile requiring the newest version.

I might suggest that we draft a short note on the new features of 2.1 and include a comment on the need to upgrade (for free) to Reader/DSS v8.x from Ventana.

**Comment by jrissman** [comment]
System requirements updated in commit 7c136b1.  I've uninstalled 32-bit Vensim 7 (both DSS and Model Reader) from my system and will be developing and testing the EPS only in 64-bit Vensim 8 going forward.

**Comment by mkmahajan** [comment]
Updated guidance text on commit da0b77c. I also tested the PERAC and BPEiC, but made no changes.
