### ISSUE TITLE
Calculate total output by ISIC code

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#200]
One thing that would be nice to have is an estimate of total output by ISIC code. Right now we have BAU output by ISIC code by year, direct change in output (which is from industry changes) and induced change (from household and government spending changes) but we don't calculate the indirect change in output and we don't sum these anywhere in the model. Since we have all the pieces it would be nice to calculate this. We are participating in a modeling exercise where this is a very common output across many different climate and energy models, so it would be an output used broadly by similar types of models.

**Comment by jrissman** [comment]
Completed in 5b78d98.  The value you want is in the new variable `Domestic Output by ISIC Code` on the `Input-Output Model` sheet.
