### ISSUE TITLE
Add soil carbon management as a geoengineering/LULCUF option

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#201]
Soil carbon management involves changing practices to sequester CO2 in soils. We currently have no process emissions reductions policies that sequester CO2 or reduce CO2 in agriculture, because the EPA data only covers non-CO2 gases. However, we have new data from ICF/Dept of Ag that has MACC curves for agriculture practices that sequester CO2. Normally, we would just put this into PERAC, but the soil sequestration amounts exceed the BAU process emissions because it's really carbon removal. So either we could allow for negative values or we would need to assign soil carbon management to a different sector. The potential is significant, possibly 60-70 MMT in the US, and worthy of inclusion. @oashmoore received the public dataset and has a copy.

**Comment by jrissman** [comment]
Steps:
1. Add to PERAC as CO2 reduction
2. Use zero emissions as the baseline, and all effects of this new policy generate negative agricultural CO2 emissions

Determine if we want to address permanence of CO2 sequestration.

**Comment by robbieorvis** [comment]
Attaching relevant files from the BBB analysis modeling we did with MACC curves for ag soils. This version of PERAC has a new tab and data for agriculture-tillage that reflects the data. I'm also uploading the source .xlsx file. Here is the link to study it originates from: https://www.usda.gov/sites/default/files/documents/White_Paper_WEB_Final_v3.pdf
[Proc Emis Reductions and Costs.xlsx](https://github.com/Energy-Innovation/eps-us/files/8090513/Pro
[MACC Data 11.5.2021.xlsx](https://github.com/Energy-Innovation/eps-us/files/8090537/MACC.Data.11.5.2021.xlsx)
c.Emis.Reductions.and.Costs.xlsx)
.

**Comment by jrissman** [comment]
Programming of this feature is done.  It is currently using stand-in data (csv file), so it still needs a PERAC update.

**Comment by mkmahajan** [comment]
I finished the data for this issue and also added tillage measures to the web app and the NDC scenario, which we had not done during our previous work.
