### ISSUE TITLE
Modify CCS capital cost calculations to reflect variation in operating capacity of power plants

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#211]
Current structure in the model uses a fixed capital cost value in $/ton-yr to estimate the capital costs of installing CCS equipment at power plants.

For example, if a coal plant emitted 1 million tons per year and the cost was $800/ton*yr, then the estimated retrofit cost would be $800 million. 

This approach however ignores that the plants don't run at a fixed capacity factor year round, but instead ramp up and down. This is especially important for peaker plants, which only run about 10% year.

The size of the CCS equipment needs to accommodate the emissions when the plants are running at 100%, not just when they run at their average capacity factors, because there will be times when the plants are operating at near 100%. 

For example, using natural gas peakers as an example, let's say a 1 MW plant runs 876 hours pear year, producing 1 ton per hour when it runs. At at a retrofit cost of $800/ton*yr, that would result in costs of roughly $700,800 _and the CCS equipment would be sized to capture 876 tons/yr / 8670 hours per year = 0.1 tons/hour_. However, the plants don't run on average at 10% of their rated capacity every hour of the year. Instead, they run at 100% of their installed capacity for ten percent of the hours of the year (i.e. produce one ton per hour, not 0.1 tons per hour, when running). That means the equipment actually has to be sized to capture the emissions as if those plants had a capacity factor of 100%. That would increase the costs by an order of magnitude. Capital costs scale proportionately with the tonnage to be captured so it would be appropriate to divide by the capacity factor.

I think this can be solved in the EPS by dividing the current capital costs calculated as part of the CCS policy by the capacity factor for each plant type, which should correctly size the CCS equipment to fully capture the plant's emissions. This will have a very important impact on estimates in the cost curves and will correctly reflect the fact that lower capacity factor resources have higher CCS costs because they run more irregularly.

**Comment by jrissman** [comment]
This seems relatively straightforward and should not be a lengthy edit.

Edits are frozen pending the 3.3.1 release, but we can start making edits for 3.3.2 once the 3.3.1 release is finalized and tagged in GitHub.

**Comment by jrissman** [comment]
Completed.
