### ISSUE TITLE
Demand response capacity and generation should reduce peaker capacity factors and generation

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#215]
Currently demand response deployment in the model can reduce emissions by avoiding the new for new peaker plants that run at a fixed capacity factor and/or adding grid flexibility that avoids curtailment. But if there is no demand for new peaker plants and there is not curtailment, the addition of DR doesn't result in any emissions reductions.

In reality, adding DR to the system would result in decreased dispatch of peaker plants.  We should account for this emissions reduction.

The EIA has data on capacity and energy saved from DR in form 861. We could use this to develop a capacity factor for demand response and multiply it by the total installed capacity in a given year to find the MWh of DR dispatched in given year. We would then need to reduce the capacity factors of peaker plants to account for the increased dispatch from demand response. We ought to reduce to electricity generation by the same amount, since DR _avoids_ generation.  

Though it may not show up as a huge amount in the current US model, DR is being heavily deployed in policy scenarios and we would expect it to have some emissions reductions even if there's no need for new peakers.

**Comment by mkmahajan** [comment]
The structure for this issue is complete. But the new file elec/DRCF is still using placeholder data, so we need to come back and address this file. Adding myself to this issue to finish off the data needs.

**Comment by mkmahajan** [comment]
Data for elec/DRCF completed using EIA Form 861.
