### ISSUE TITLE
Labor productivity growth rates should be time-series data, not constant

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#218]
Currently, the variable and data for the Labor Productivity Growth Rate by ISIC Code is a constant, not a time series. The challenge is that, especially for developing economies, the growth rate will change over time as the economies become more industrialized. We cannot currently represent this change though given the use of constants instead of time series. We should move to time series. I have found a few interesting papers on ways to approximate the evolution of growth rates over time as countries modernize, which we could use to help calculate future values.

**Comment by mkmahajan** [comment]
Completed. The US continues to use the same value in every year, but the file now allows for time series data.
