### ISSUE TITLE
Fix bug in MOfEDS formula

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#225]
The Get Direct Constants formula for MOfEDS is missing a term, so it pulls the same value for all power plant types rather than allowing for custom values by power plant. This is an easy fix that I will make for 3.4.

**Comment by jrissman** [comment]
I don't see what term is missing.  Though I do notice the function being used, GET DIRECT CONSTANTS, is not the one we are supposed to use with time-series data.  So it seems like the function ought to be GET DIRECT DATA.

**Comment by mkmahajan** [comment]
Yes, I mistakenly thought there was a missing term at first before realizing we needed the different formula.

We actually needed this edit in order for the Mexico results to make sense for the electricity sector, and had to make the last minute decision last week to make the edit for Mexico and push it out as 3.3.1.1 (in time for Friday's launch and webinar). We intended to quietly push out a US 3.3.1.1 this week to match, which I will do today. I can make a side branch for just this issue and merge that into main for a 3.3.1.1, then also make the corresponding change on top of the other 3.4 edits we've been working on.

**Comment by jrissman** [comment]
Sounds good, thank you.

**Comment by mkmahajan** [comment]
Issue complete (new 3.3.1.1 release created and edit done in develop branch)
