### ISSUE TITLE
Revert electricity dispatch to ALLOCATE AVAILABLE

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#238]
Robbie has indicated that while logit functions are preferred for power plant construction (technology selection) and vehicle sales (technology selection), the older approach with ALLOCATE AVAILABLE was preferable for electricity dispatch.  The area under the bell curves is known for electricity dispatch (it is the quantity of electricity that could be produced by existing plants of each type) but was not knowable for the other topics (i.e. the amount of vehicles or power plants of a given type that could be produced in a given year).

This will revert the change described in issue #180.

@robbieorvis - Do we want to remove logit function-based dispatch entirely, or do you think there are EPS regions where logit-based dispatch will remain preferable to ALLOCATE AVAILABLE dispatch, and you want the algorithm used to be customized by region (using a Boolean Input data flag indicating which method the computer should use for that region)?

**Comment by jrissman** [comment]
ALLOCATE AVAILABLE for electricity dispatch was removed in release 3.3.1, so we can refer to release 3.3.0 to obtain the most recent code where it was implemented and manually port it into the current model on the "develop" branch.

**Comment by jrissman** [comment]
The structure for this is done, but it needs input data updates (for example, to move renewables back out of the guaranteed dispatch section, and a review of the prices and normalized standard deviations, etc.) to make sure the input data reflect the needs of dispatch under ALLOCATE AVAILABLE rather than under the removed logit function.  @mkmahajan has indicated she can do the input data parts now.

**Comment by mkmahajan** [comment]
I've made some edits to the input data to reflect the change back to ALLOCATE AVAILABLE and think the electricity sector is now looking good.
