### ISSUE TITLE
Correct hydrogen production efficiency by pathway

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#26]
Double-check and fix the data in HPEbP Hydrogen Production Efficiency by Pathway.

In an email from 10/8/19, Robbie wrote:

> I think our values for hydrogen emissions are too low. I think this an issue with input data, in particular in HPEbP Hydrogen Production Efficiency by Pathway. I looked at the source data for this variable, which is taken from an IEA report and assumes an efficiency of >70% for methane reforming. I think there is a misunderstanding here about what the efficiency value means. My understanding is that this efficiency value relates to the chemical conversion process, i.e. that 1 btu of CH4 in produces ~0.7 btu of H2 out, not that this has to do with the total energy used in the process. In fact, the same IEA report states that 30-40% of natural gas consumed in these plants is used for energy purposes, not for the chemical conversion. I think this is reiterated by the fact the calculated emission rate using the efficiency value in the model right now is about 0.065 g CO2/BTU, but using the g CO2/kg H2 factor from that same IEA report and a standard heat content of hydrogen of 120 MJ/kg results in an emissions rate of 0.078 g CO2/BTU, or about 20% higher than what we have now.

**Comment by robbieorvis** [comment]
Done in commit https://github.com/Energy-Innovation/eps-us/commit/a1bf10b9260563fd17c40a618e01f515d6e46908
