### ISSUE TITLE
Update BAU Demand Response Capacity and Additional Potential

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#28]
Existing data is somewhat old and we have some new sources on existing and potential data. 

See: https://www.brattle.com/news-and-knowledge/news/brattle-research-on-national-potential-for-load-flexibility-featured-in-annual-sepa-demand-response-market-snapshot

**Comment by mkmahajan** [comment]
Completed with commit a700f80 to data branch
