### ISSUE TITLE
Fix MPPC placement in main vs BAU capacity retirement calculation

### ISSUE THREAD

**Issue by dobrien13** [Energy-Innovation/eps-us#301]
MPPC Minimum Power Plant Capacity should be applied to retiring capacity at the same point in BAU and main electricity sheets - caused BAU-Policy differences in EU EPS 4.0 without levers

**Comment by robbieorvis** [comment]
Sure thought I fixed this with the last commit, but maybe I didn’t push it.
Sent from my iPhone

On Apr 23, 2024, at 2:48 PM, dobrien13 ***@***.***> wrote:

﻿

Assigned #301<https://github.com/EnergyInnovation/eps-us/issues/301> to @robbieorvis<https://github.com/robbieorvis>.

**Comment by dobrien13** [comment]
I just came back here to say the same @robbieorvis -- we hadn't pulled it into EU...oh well, good debugging practice.
