### ISSUE TITLE
Add maintenance costs for different vehicle and technology types and account for changes in maintenance cash flow to various actors.

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#36]
We currently omit differences in maintenance costs for different vehicle types, but this is important part of the consideration for/against moving to EVs for the auto industry and for consumers. We should add in changes in annual maintenance costs for different technologies to account for these differences.

**Comment by jrissman** [comment]
Finished in commit 5e4477b, including input data and model structure.

Accounting for the differences in annual maintenance costs by vehicle technology does drive some additional adoption of electric vehicles.  The graph below shows transportation sector CO2 after I'd added maintenance costs to the policy case but before I added them to the BAU case (to illustrate the effect of the new calculations - no policies are actually enabled).

![MaintCostEffect](https://user-images.githubusercontent.com/7120106/79383751-942bd800-7f1a-11ea-81d2-4bc348f8c172.PNG)

Of course, in the finished commit, the maintenance costs are added to both BAU and policy cases, so the two lines overlap.
