### ISSUE TITLE
Update variable Fraction of Surviving Peaking Capacity by Type to use ZIDZ

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#37]
The variable Fraction of Surviving Peaking Capacity by Type estimates the share of surviving peaking capacity by type. In some regions, there may be no explicit peaking capacity remaining, although there is sufficient capacity with high enough peak time capacity factors to meet peak demand. In these cases, the model produces a floating point error because it is dividing by zero. Here the formula for this variable should be updated to:

ZIDZ(SUM(Surviving Electricity Generation Capacity[Electricity Source,Power Plant Quality!])
* BPaFF Boolean Is This Plant Type a Peaker[Electricity Source],
SUM(Surviving Electricity Generation Capacity[Electricity Source!,Power Plant Quality!]
      * BPaFF Boolean Is This Plant Type a Peaker[Electricity Source!]))

**Comment by jrissman** [comment]
Finished in commit 87640ca.
