### ISSUE TITLE
Remove 'Nuclear Plant Lifetime Extension' policy from web app

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#39]
EIA's data does not assume plants retire after their license expires and instead assumes the plants continue with higher operating costs.

**Comment by jrissman** [comment]
I don't see this.  There are non-zero nuclear retirements in elec/BCRbQ.  And, accordingly, the nuclear lifetime extension lever has an effect.  Therefore, it seems to me that it should remain in the web app.

**Comment by mkmahajan** [comment]
This is something I looked into this week, comparing to NRC data on reactor status. The Assumptions to the AEO state:
Fossil-fired steam plant retirements and nuclear retirements are determined endogenously within the model. Generating units are assumed to retire when continuing to run them is no longer economical. Each year, the model determines whether the market price of electricity is sufficient to support the continued operation of existing plant generators. A generating unit is assumed to retire if the expected revenues from the generator are not sufficient to cover the annual going-forward costs and if the overall cost of producing electricity can be lowered by building replacement capacity. The going-forward costs include fuel, O&M costs, and annual capital expenditures (CAPEX), which are unit-specific and based on historical data. The average annual capital additions for existing plants are $10 per kW for oil and natural gas steam plants and $26 per kW for nuclear plants (in 2018 dollars). These costs are added to the estimated costs at existing plants regardless of their ages. Beyond 30 years old, an additional $36 per kW capital charge for nuclear plants is included in the retirement decision to reflect further investment to address the impacts of aging. Age-related cost increases are attributed to capital expenditures for major repairs or retrofits, decreases in plant performance, and/or increases in maintenance costs to reduce the effects of aging.

If you compare the NRC status of US reactors, it's clear that EIA assumes reactors continue to receive extensions. By shifting the retirement date for retirements in elec/BCRbQ, we are actually shifting out plants like Diablo Canyon that already have set retirement dates, rather than allowing for more license extensions.

**Comment by jrissman** [comment]
Okay, so, is it fair to say that the retiring nuclear capacity currently in BCRbQ only includes capacity with announced retirement dates, which are very unlikely to be extended?  (And this is why we don't see any additional retirements there beyond 2036, probably)?  And all other nuclear plants don't appear in BCRbQ even if their licenses would run out during the model run period?

**Comment by jrissman** [comment]
Sorry, beyond 2032, not 2036

**Comment by mkmahajan** [comment]
Yes, that is correct.

**Comment by jrissman** [comment]
Okay, I agree with you about what to do.  Thank you for explaining that more fully to me.  I appreciate it! 😄

**Comment by jrissman** [comment]
Done, will be included in upcoming 2.1.1 release
