### ISSUE TITLE
Consider allowing policy implementation schedules to vary by subscript

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#44]
As we are asked to model more aggressive policy scenarios, this issue has come up multiple times. Policymakers are interested in 100% EV sales targets for LDVs by 2030 or 2035, but HDVs and other vehicle types need a longer lead time. Breaking out the implementation schedule for at least LDVs would help us address the different decarbonization timelines for various vehicle types.

**Comment by jrissman** [comment]
This isn't something that could be done on a policy-by-policy basis.  This is a change that would affect all policies globally.  It requires work both in Vensim and on the web interface's underlying data management.

**Comment by jrissman** [comment]
I think we would have more bandwidth for this when we have a Full Stack Developer FTE.

**Comment by jrissman** [comment]
Wait, we already have this in the issue tracker.  Closing as a duplicate of #16.
