### ISSUE TITLE
Recalibrate power sector retirement from changes in costs using new EIA data

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#48]
A new set of EIA side cases on carbon pricing provides us with a great new data source for calibrating the elec/ARpUIiRC for the next model update.

Link: https://www.eia.gov/todayinenergy/detail.php?id=43176 (also can be accessed as a set of AEO side cases)

**Comment by mkmahajan** [comment]
Completed with commit ec2caca
