### ISSUE TITLE
Allocate electricity sector construction costs (and possibly building component costs) to ISIC sectors beyond just construction based on data on spending shares

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#65]
Hi Robbie,

If you want to send a file with power plant type on one axis and a breakout of construction cost by ISIC code on the other, I should be able to use that.  Construction costs should be allocated by ISIC code, including the ISIC code for “construction” which would cover the physical buildings housing the power generating equipment, grading of the land, construction of retention or cooling ponds, and other tasks involved in building power plants that aren’t actually about procuring the equipment.  I assume the three most relevant ISIC codes will be “construction,” “machinery,” and “electrical equipment.”

I also need the share of spending on new power plant construction that goes to labor, but you can give me that number separately, rather than in the file with power plants and ISIC codes.  We don’t have an ISIC code for “labor” or “households.”  In the EPS, “construction” is not the same thing as “labor.”

What about the spending on constructing transmission lines?  How about on decommissioning (which I assume is largely demolition, waste disposal, and site remediation)?  How do you want me to allocate those expenditures?  Currently, they’re all going to the “construction” ISIC code.

For buildings, if you don’t want me to allocate it all to construction, I can use data splitting up spending by ISIC code.  But note that we already have a variable called “SYSoCCtaSC Share of Distributed Solar and Retrofitting Costs that is Labor” – maybe that variable can be used to separate out the labor share of all construction costs, not just distributed solar and retrofitting.  I think it’s probably unhelpfully precise to use different labor shares for different buildings sector construction activities.  As for the non-labor portion of the spending, did you want to divide it by building component, so that spending on “envelope” improvements go to construction, “heating” and “appliances” improvements go to “machinery,” and lighting improvements go to “electrical equipment,” etc.?

**Comment by jrissman** [comment]
Completed in 11357aa.
