### ISSUE TITLE
Modify peaking calculations to account for shift in demand from electrification

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#68]
We currently assess peaking needs looking at the single peak season, because historically this has been appropriate. But in high electrification scenarios, we may see a shift in peaking, or a biannual peak in winter and summer, during which resources have different peak time capacity factors.

To correctly account for this, we need to probably calculate seasonal peaks, based on the demand from different sectors and then to do a check in the power sector against both seasonal peaks. 

I can think a bit more about how to handle this, but it is increasingly important in deep decarbonization scenarios. 

@jrissman maybe we can talk through some ideas for this.

**Comment by robbieorvis** [comment]
I found a very interesting potential resource for this: https://openei.org/doe-opendata/dataset/commercial-and-residential-hourly-load-profiles-for-all-tmy3-locations-in-the-united-states

DOE has published hourly load data by end use for residential and commercial buildings around the country. We could pick a few representative cities, put this in Excel, then calculate the estimated impact of shifting appliances to all electric and see the impact on peak demand in each day. We could then estimate seasonal peak load and perhaps create a multiplier of peak load shift to electrification, where a BTU of shifted energy for each end use and building type has a corresponding increase on the peak time capacity requirement, e.g., each BTU shifted from gas or oil to electricity has X impact on peak load.

Can look into this some more next week, but this seems quite promising.

**Comment by robbieorvis** [comment]
Here's the process for how we could do this Vensim after playing around with this today:

1) Sum the total hourly electricity demand across all cities in the dataset linked above. We need to account for time zone differences. The final result would be a single set of hourly consumption by equipment and fuel type in buildings.

2) Identify the system load factor for total gas and other equipment end use, i.e., the ratio of peak demand for the service/fuel to annual demand for that service and fuel. This gets read in as an input file.

3) In Vensim, we would calculate the annual change in BTU of fuel to electricity from the electrification lever, then use the system load factor to identify the shift in peak consumption, adjusting for improved efficiency of electrified equipment compared to baseline. (We already have this - it's just the increase in the electricity demand from the electrification lever in a given year). Dividing by the load factor gives us the net increase in btu of electricity demand at the peak. 

4) Convert to kW to identify the additional peak demand need from power plants.

5) Taking winter system load factor data for the grid, add that capacity on top of whatever we calculate for the peak demand before electrification (like how we do now for the single season peak calculations). 

6) Switch from peak time capacity factors to seasonal peak time capacity factors, with one for winter and one for summer.

7) Two allocations for peak power plants to ensure summer and peak demand are both met; potentially the demand could be combined into a single value to a single allocation.

This sounds like a lot of work but is has a **huge** impact on the required system build out and associated costs. For example, Looking at just electrifying heating in residential buildings in the EPS, I found this ends up requiring an additional _100 GW of peak time capacity in the winter, which is roughly 10% of the power system size in the US._ Add into that the fact that this may have to be met by renewables with lower capacity factors and you are talking hundreds of GW of additional capacity that is needed to meet this demand (e.g. if with wind only, this would require 200-300 GW extra wind). This will also make the DR and storage policies much more effective, and probably more cost-effective.

**Comment by jrissman** [comment]
Maybe we should walk through this through in a screen sharing session.  I think I follow the overall outline here, but it would be helpful to see it on your screen and you can walk me through it.

One thing I don't quite understand is why you propose looking at electricity demand from shifting away from other fuels differently from other types of electricity demand growth.  The grid only cares how many electric cars there are, not whether they displaced gasoline cars, or whether they are simply new cars that people can now afford due to an increase in wealth of the modeled region.  (We see tons of electricity demand growth that is not associated with fuel shifting in rapidly-developing regions like India and Indonesia, especially for air conditioning.)  So I'd be inclined to use as inputs to this calculation properties the grid sees (e.g. how many electric cars, air conditioners, etc. there are) and not whether that electricity demand growth is due to fuel shifting.

**Comment by jrissman** [comment]
Also, the discussion of winter and summer peaks sounds specific to temperate countries.  How would this proposed modification work in very hot countries or very cold countries?  That city list you found seems U.S.-specific, so we should make sure this makes sense in an international context.

**Comment by robbieorvis** [comment]
Sure, we can do that next week, if you'd like.

Growth in total electricity demand is covered by the existing structure which divides the annual electricity demand by the peak time capacity factor. Assuming there is no seasonality to the increase demand (for example, probably not much from EVs), then the existing structure works fine because the peak part of the year remains the same.

The issue here is we are converting from thermal fuels to electricity for an end use which is highly seasonal in nature, specifically space heating. This is the reason we need new structure; the current structure only allows for a single annual demand peak but we need to be able to model summer and winter.

In very hot countries, there is unlikely to be much if any heating demand, so this addition is probably not meaningful, except to the extent resource output from renewables changes with the seasons.

In very cold countries, it is likely that the "peak time" already covers the winter, so it may not be adding a lot of value, though it is likely that an increase in the annual electricity demand from additional electric heating would have greater-than-proportional impact on the system load factor (ratio of peak demand to average demand) because it would be consolidated to a single season.

But in all cases, this structural change would improve accuracy in the power sector and help rectify a longstanding issue with missing seasonal peak demand and differences in the seasonal output of various sources. 

I think for all countries we could pick some of the US cities as indicators by comparing the annual heating and cooling degree data, so it would not be too challenging to internationalize if those countries don't have this data.

**Comment by robbieorvis** [comment]
Quick look at the data suggests elec/PTCF and elec/SLF already have the data needed for part of this structure (the winter system load factor and peak time capacity factors for variable resources).

**Comment by robbieorvis** [comment]
Robbie to create:

elec/SLF with seasonal outputs
elec/PTCF with seasonal outputs
Peak demand multipliers for building sector end-uses for electricity

**Comment by robbieorvis** [comment]
@jrissman almost have the data for you but have been thinking about a comment you made on our call. The existing system load factor calculations (now for seasons) will account for some of the increased demand already from electrification, so we need to make sure that the new function only adds what is missing from the calculation. In other words, we should probably calculate the additional peak MW from electrification using the BAU peak and then adding the shifted peak to that, and comparing with the policy peak, adding the delta between the two.

**Comment by jrissman** [comment]
Completed in b0d9bab, 15e432b, 58c1e73, 4c06f14, 98597ea, and 332a359.
