### ISSUE TITLE
Bug in calculating distributed solar PV costs and solution

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#83]
I found a bug in the calculation of distributed solar subsidy costs. 

For the calculation of _Subsidy Paid on Distributed Solar Capacity_, the variable _Perc Subsidy for Distributed Solar PV Capacity_ is used, but instead it should be _Perc Subsidy for Distributed Solar PV Capacity this Year_

**Comment by jrissman** [comment]
Thank you for finding this!  Fixed in f467cec.
